[tool.poetry]
name = "spotify_app"
version = "0.1.0"
description = "Demo the spotify auth, API calls, and some plotly viz"
authors = ["Shoup <dave.shoup@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
dash = "^2.0.0"
Flask = "^2.0.2"
dash-bootstrap-components = "^1.0.2"
pandas = "^1.3.5"
plotly = "^5.5.0"
spotipy = "^2.19.0"
dash-mantine-components = "^0.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
